    ingester:
      chunk_encoding: snappy
    limits_config:
      allow_structured_metadata: true
      ingestion_burst_size_mb: 200
      ingestion_rate_mb: 100
      max_cache_freshness_per_query: 10m
      max_entries_limit_per_query: 100000
      max_streams_per_user: 0
      per_stream_rate_limit: 50MB
      per_stream_rate_limit_burst: 100MB
      query_timeout: 300s
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      retention_period: 720h
      split_queries_by_interval: 15m
      volume_enabled: true
    memberlist:
      join_members:
      - loki-memberlist
    pattern_ingester:
      enabled: true
    query_range:
      align_queries_with_step: true
      cache_results: true
      results_cache:
        cache:
          background:
            writeback_buffer: 500000
            writeback_goroutines: 1
            writeback_size_limit: 500MB
          default_validity: 12h
          memcached_client:
            addresses: dnssrvnoa+_memcached-client._tcp.automation-loki-results-cache.automation.svc
            consistent_hash: true
            timeout: 500ms
            update_interval: 1m
    ruler:
      storage:
        gcs:
          bucket_name: observe-472521-automation-loki-ruler
          chunk_buffer_size: 0
          enable_http2: true
          request_timeout: 0s
        type: gcs
    runtime_config:
