---
# Keycloak Configuration Playbook
# Configures NetBird OAuth clients in Keycloak (deploy or external mode)
# All configuration is in group_vars/keycloak.yml
#
# NOTE: Run setup_and_run.yml instead of this file directly
#       It will install required collections first

- hosts: keycloak
  become: yes
  roles:
    - role: keycloak
      # All variables are read from group_vars/keycloak.yml
      # No need to override here unless testing specific values