apiVersion: v2
name: monitoring-stack
description: Umbrella chart for NetBird monitoring stack (Loki, Prometheus, Grafana, Mimir)
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: loki
    version: "6.6.4"
    repository: "https://grafana.github.io/helm-charts"
    condition: loki.enabled
  
  - name: prometheus
    version: "25.27.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: prometheus.enabled
  
  - name: grafana
    version: "8.4.4"
    repository: "https://grafana.github.io/helm-charts"
    condition: grafana.enabled
  
  - name: mimir-distributed
    version: "5.5.0"
    repository: "https://grafana.github.io/helm-charts"
    condition: mimir-distributed.enabled