# Global configuration
global:
  labels:
    cluster: <CLUSTER_NAME> # Replace with your cluster name
    environment: <ENVIRONMENT> # Replace with your environment (e.g., production, staging, development)

# Enable/disable components
loki:
  enabled: true

prometheus:
  enabled: true

grafana:
  enabled: true

mimir-distributed:
  enabled: true

tempo-distributed:
  enabled: true

