apiVersion: v1
kind: Service
metadata:
  name: loki-nodeport
  namespace: monitoring
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: single-binary
spec:
  type: NodePort
  ports:
    - name: http
      port: 3100
      targetPort: http-metrics
      nodePort: 31100
      protocol: TCP
  selector:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: single-binary
    app.kubernetes.io/instance: monitoring-stack