apiVersion: v1
kind: Service
metadata:
  name: tempo-external
  namespace: monitoring
  labels:
    app.kubernetes.io/name: tempo
    app.kubernetes.io/instance: monitoring-stack
spec:
  type: NodePort
  ports:
    - name: tempo-http
      port: 3200
      targetPort: 3200
      nodePort: 31200
      protocol: TCP
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
      nodePort: 31317
      protocol: TCP
    - name: otlp-http
      port: 4318
      targetPort: 4318
      nodePort: 31318
      protocol: TCP
    - name: jaeger-thrift-http
      port: 14268
      targetPort: 14268
      nodePort: 31268
      protocol: TCP
  selector:
    app.kubernetes.io/name: tempo
    app.kubernetes.io/instance: monitoring-stack